"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".about[_ngcontent-%COMP%] {\n  display: block;\n  padding: 0.5rem;\n  font-family: var(--font-family);\n  grid-gap: 1rem;\n  font-size: 1.28rem;\n\n  @media (min-width: 600px) {\n\n    display: grid;\n    grid-template-columns: 55% 43%;\n    grid-template-rows: max-content;\n    grid-template-areas: \"slideshow title\" \"slideshow description\";\n    grid-gap: 1rem;\n    align-content: start;\n  }\n\n  &__title {\n    grid-area: title;\n\n  }\n\n  &__main-title {\n    margin: 0;\n    font-family: var(--title-font-family);\n    font-size: 2.28rem;\n    //width: 70%;\n    white-space: pre-wrap;\n    white-space: -moz-pre-wrap;\n    white-space: -o-pre-wrap;\n    word-wrap: break-word;\n  }\n\n  &_slideshow {\n    grid-area: slideshow;\n  }\n\n  &__price {\n    font-size: 2.28rem;\n    color: var(--green-color);\n    margin-left: 1.2rem;\n  }\n\n  &__description {\n    grid-area: description;\n    padding-top: 1rem;\n    //width: 80%;\n    white-space: pre-wrap;\n    white-space: -moz-pre-wrap;\n    white-space: -o-pre-wrap;\n    word-wrap: break-word;\n  }\n\n  &__list {\n    box-sizing: border-box;\n    margin: 0;\n    padding: 0 2rem;\n    list-style: none;\n  }\n\n  &__list li:before {\n    content: '- ';\n  }\n}\n\n.no-login[_ngcontent-%COMP%]{\n  font-family: var(--font-family);\n  color: var(--content-color);\n  font-size: 2rem;\n  font-weight: bold;\n}\n\n.edit-btn[_ngcontent-%COMP%]{\n  float: right;\n  font-size: 1.2rem;\n  font-weight: bold;\n}"];
exports.styles = styles;
//# sourceMappingURL=product-detail-page.component.scss.shim.ngstyle.js.map