"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".btn-on-top[_ngcontent-%COMP%] {\n  position: fixed;\n  z-index: 77;\n  bottom: 5rem;\n  right: 2rem;\n  border-radius: 50%;\n  width: 3rem;\n  height: 3rem;\n  font-size: 1.6rem;\n  background-color: var(--theme-color);\n  color: var(--sub-theme-color);\n  outline: none;\n\n  &:hover {\n    background-color: var(--green-color);\n  }\n}"];
exports.styles = styles;
//# sourceMappingURL=button-on-top.component.scss.shim.ngstyle.js.map