"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["footer[_ngcontent-%COMP%] {\n  position: fixed;\n  bottom: 0;\n  z-index: 88;\n  -webkit-box-sizing: border-box;\n  -moz-box-sizing: border-box;\n  box-sizing: border-box;\n  height: 50px;\n  width: 100%;\n  font-family: var(--font-family);\n  font-size: 1.28rem;\n  font-weight: bold;\n  background: var(--theme-color);\n  color: var(--sub-theme-color);\n  margin-top: 15px;\n  padding-top: 15px;\n  text-align: center;\n}"];
exports.styles = styles;
//# sourceMappingURL=footer.component.scss.shim.ngstyle.js.map