"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".profile__avatar[_ngcontent-%COMP%]{\n  width: 10rem;\n  height: 10rem;\n  margin: 2rem auto;\n}"];
exports.styles = styles;
//# sourceMappingURL=profile-page.component.css.shim.ngstyle.js.map