"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".images-loader[_ngcontent-%COMP%] {\n  display: flex;\n  flex-flow: row wrap;\n  //border: 1px solid gray;\n  box-sizing: border-box;\n  padding: 0;\n\n  &__item {\n    display: flex;\n    justify-content: stretch;\n    align-items: stretch;\n    position: relative;\n    height: 10rem;\n    width: 10rem;\n    margin: 0.5rem;\n    //border: 1px solid gray;\n\n    img {\n      position: absolute;\n      height: 100%;\n      width: 100%;\n    }\n  }\n\n  ._uploaded {\n    border: 2px solid var(--green-color);\n  }\n\n  _new {\n\n  }\n\n  &__label {\n    display: flex;\n    justify-content: center;\n    align-items: center;\n    height: 5rem;\n    width: 5rem;\n    margin: auto;\n    overflow: hidden;\n    position: relative;\n    border-radius: 50%;\n    background-color: var(--green-color);\n    color: white;\n    font-size: 4rem;\n    font-weight: 900;\n    //cursor: pointer;\n  }\n\n  &__input {\n    cursor: pointer;\n    margin: 0;\n    //display: block;\n    //font-size: 999px;\n    //filter: alpha(opacity=30);\n    box-sizing: border-box;\n    //height: 100%;\n    //width: 100%;\n    border-radius: 50%;\n    opacity: 0;\n    position: absolute;\n    //right: 0;\n    //text-align: right;\n    //top: 0;\n  }\n\n  &__btn{\n    cursor: pointer;\n    position: relative;\n    z-index: 99;\n    width: 100%;\n    font-size: 3rem;\n    opacity: 0;\n    //background-color: white;\n  }\n\n  &__btn:hover{\n    //display: block;\n    opacity: 50;\n  }\n\n\n}"];
exports.styles = styles;
//# sourceMappingURL=images-uploader.component.scss.shim.ngstyle.js.map