"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".slideshow[_ngcontent-%COMP%] {\n  \n  width: 100%;\n  position: relative;\n  box-sizing: border-box;\n  padding: 0;\n\n&__slide {\n\nimg {\n  width: 100%;\n}\n}\n\n&__nav {\n   display: flex;\n   justify-content: space-between;\n }\n\n&__btn {\n   display: flex;\n   justify-content: center;\n   align-items: center;\n   width: 50px;\n   cursor: pointer;\n   position: absolute;\n   height: 100%;\n   top: 0;\n   color: black;\n   transition: 0.6s ease;\n }\n\n&__btn:hover {\n   background-color: rgba(255, 255, 255, 0.6);\n }\n\n&__btn_next {\n   right: 0;\n }\n\n&__btn_active {\n   background-color: #717171;\n }\n\n\n&__slide_fade {\n   -webkit-animation-name: fade;\n   -webkit-animation-duration: 1.5s;\n   animation-name: fade;\n   animation-duration: 1.5s;\n }\n}\n\n@-webkit-keyframes fade {\n  from {\n    opacity: .4\n  }\n  to {\n    opacity: 1\n  }\n}\n\n@keyframes fade {\n  from {\n    opacity: .4\n  }\n  to {\n    opacity: 1\n  }\n}"];
exports.styles = styles;
//# sourceMappingURL=slideshow.component.scss.shim.ngstyle.js.map