"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".product-list[_ngcontent-%COMP%]{\n  width: 100%;\n  display: flex;\n  flex-flow: row wrap;\n  justify-content: center;\n}"];
exports.styles = styles;
//# sourceMappingURL=product-list-page.component.scss.shim.ngstyle.js.map