"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".product-item[_ngcontent-%COMP%] {\n  height: 250px;\n  width: 320px;\n  margin: 0.72rem;\n\n  @media (max-width: 700px) {\n    width: 220px;\n  }\n\n  @media (max-width: 500px) {\n    width: 100%;\n  }\n\n  &__url {\n    height: 100%;\n    display: flex;\n    flex-flow: column nowrap;\n    align-items: stretch;\n    justify-content: stretch;\n    box-sizing: border-box;\n    color: var(--sub-theme-color);\n    background-color: var(--theme-color);\n    text-decoration: none;\n  }\n\n  &__url:hover {\n    background-color: var(--green-color);\n  }\n\n  &__img {\n    max-height: 200px;\n    max-width: 100%;\n    height: 100%;\n    padding: 0;\n    margin: 0;\n  }\n\n  &__title {\n    display: inline-flex;\n    align-items: center;\n    justify-content: space-between;\n    margin: 0;\n    box-sizing: border-box;\n    padding: 0 1rem;\n    font-family: var(--font-family);\n    font-size: 1.28rem;\n    font-weight: bold;\n    height: 3.6rem;\n    word-wrap: break-word;\n    word-break: break-all;\n  }\n\n  &__ico {\n    flex: 2rem;\n    font-size: 2rem;\n  }\n}"];
exports.styles = styles;
//# sourceMappingURL=product-item.component.scss.shim.ngstyle.js.map