"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".login-logo[_ngcontent-%COMP%] {\n  text-align: center;\n}\n\n\n.login-right-section[_ngcontent-%COMP%] {\n  position: absolute;\n  top: 0;\n  right: 0;\n  display: flex;\n  flex-flow: column nowrap;\n  justify-content: space-between;\n  -webkit-box-sizing: border-box;\n  -moz-box-sizing: border-box;\n  box-sizing: border-box;\n  padding: 0 1.85rem;\n  overflow-y: auto;\n  overflow-x: hidden;\n  width: 383px;\n  height: 100vh;\n  background: var(--theme-color);\n\n  &_bottom-text {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n    padding: 8rem 0 1rem 0;\n    width: 100%;\n    font-family: var(--font-family);\n    color: var(--sub-theme-color);\n    text-align: center;\n    font-size: 1rem;\n    font-weight: normal;\n  }\n}\n\n\n.login-left-section-image[_ngcontent-%COMP%] {\n  height: 100vh;\n  background: #eee6e3;\n\n  &__img {\n    position: absolute;\n    bottom: 0;\n    left: 0;\n    \n    width: calc(100% - 370px);\n  }\n}"];
exports.styles = styles;
//# sourceMappingURL=login-page.component.scss.shim.ngstyle.js.map